# Generated by Django 2.0 on 2017-12-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0005_auto_20171229_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
